fixed-2
On-line-courses/nodejs-homework-rest-api pull request #2
Opened 2023-08-28 13:24 UTC by NataliaHal

перевірте будь ласка

2023-08-28 17:26 UTC, KhYulian commented on mongoose/index.js
> +  }
для валідації використовйте виколючно joi. такі перевірки непотрібні

2023-08-28 17:27 UTC, KhYulian commented on mongoose/index.js
> +mongoose.connect(URI, { useNewUrlParser: true, useUnifiedTopology: true });
підключайтесь до бд в index.js, де у вас сервер

2023-08-28 17:27 UTC, KhYulian commented on mongoose/index.js
> +const URI = "mongodb+srv://Dfrtgh67:Dfrtgh67@cluster0.m4de63i.mongodb.net/db-contacts";
використовуйте змінні серидовища

2023-08-28 17:28 UTC, KhYulian commented on mongoose/index.js
> +app.patch('/api/contacts/:contactId/favorite', async (req, res) => {
перегляньта навчальні матеріали та лекції. роути в окремій папці, використовуйте const router = Router() і т.д.

2023-08-28 17:28 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-09-05 19:37 UTC, NataliaHal commented
перевірте будь ласка

2023-09-05 19:50 UTC, NataliaHal commented
виправлення

2023-09-06 05:39 UTC, KhYulian commented on .env.example
> +});
такого в .env.example зазвичай не пишуть)

2023-09-06 05:40 UTC, KhYulian commented on app.js
> +const routes = require("./routes/api/index.js");
.js можна не прописувати в імпортах

2023-09-06 05:40 UTC, KhYulian commented on mongoose/index.js
> +const dbURI = process.env.MONGODB_URI;
const {MONGODB_URI} = process.env;

2023-09-06 05:41 UTC, KhYulian commented on package.json
> +    "start:dev": "cross-env NODE_ENV=development node ./server.js",
start:dev - nodemon 
start - node

2023-09-06 05:42 UTC, KhYulian commented on routes/api/contacts.js
> +router.get('/:contactId', ContactControllers.getContactById, (req, res, next) => {
тут передаєте лише контроллер, а в контрелері прописуєте  res.json({ message: 'template message' }); тільки замість template message має бути справжня інформація

2023-09-06 05:42 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-09-06 09:42 UTC, NataliaHal commented
виправила, перевірте будь ласка

2023-09-07 07:04 UTC, NataliaHal commented
перевірте будь ласка

2023-09-07 17:05 UTC, KhYulian approved these changes
Чудова робота

2023-09-07 17:05 UTC, merged