04 auth
On-line-courses/nodejs-homework-rest-api pull request #3
Opened 2023-09-15 08:07 UTC by NataliaHal

перевірте будь ласка і підкажіть чому в мене не підключається база users в mongo db?

2023-09-15 16:53 UTC, KhYulian commented on app.js
> +
перевірте prettier він має форматувати надлишкові пусті рядки

2023-09-15 16:55 UTC, KhYulian commented on models/users.js
> +
const User = mongoose.model('user', userSchema);

module.exports = User;

2023-09-15 16:55 UTC, KhYulian commented on middlewares/users.js
> +function users(req, res, next) {
```suggestion
function auth(req, res, next) {
```

2023-09-15 16:55 UTC, KhYulian commented on middlewares/users.js
> +  if (bearer !== "Bearer") {
```suggestion
  if (bearer !== "Bearer" || !token) {
```

2023-09-15 16:56 UTC, KhYulian commented on controllers/users.js
> +      console.log("Email");
```suggestion
```

2023-09-15 16:56 UTC, KhYulian commented on controllers/users.js
> +    if (user === null) {
```suggestion
    if (!user ) {
```

2023-09-15 16:57 UTC, KhYulian commented on controllers/users.js
> +    await User.findByIdAndUpdate(user._id, { token }).exec();
```suggestion
без .exec() не працює
```

2023-09-15 16:57 UTC, KhYulian commented on controllers/users.js
> +  }
Винесіть функції в окремий файл e.g. controllers/userControllers.js

2023-09-15 16:57 UTC, KhYulian commented on controllers/users.js
> +});
Виносьте схеми валідації окремо e.g. /utils/validation/userValidationSchemas.js

2023-09-15 16:58 UTC, KhYulian requested changes
Потрібні правки. Відписуйте на коменти по мірі виправлення

2023-09-16 07:51 UTC, NataliaHal commented
перевірте будь ласка виправила заувження

2023-09-16 10:16 UTC, merged