не запускається сервер
On-line-courses/nodejs-homework-rest-api pull request #4
Opened 2023-09-18 11:06 UTC by NataliaHal

не запускається сервер, допоможіть будь ласка

2023-09-18 15:22 UTC, On-line-courses commented
PS C:\node.js.home-work\nodejs-homework-rest-api> npm run start:dev

> template@0.0.0 start:dev
> cross-env NODE_ENV=development nodemon ./server.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./server.js`
C:\node.js.home-work\nodejs-homework-rest-api\node_modules\@hapi\hoek\lib\assert.js:21
    throw new AssertError(args);
    ^

Error: regex must be a RegExp
    at new module.exports (C:\node.js.home-work\nodejs-homework-rest-api\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (C:\node.js.home-work\nodejs-homework-rest-api\node_modules\@hapi\hoek\lib\assert.js:21:11)
    at internals.Base.method (C:\node.js.home-work\nodejs-homework-rest-api\node_modules\joi\lib\types\string.js:541:17)
    at Object.<anonymous> (C:\node.js.home-work\nodejs-homework-rest-api\schemas\usersSchema.js:13:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)

Node.js v18.16.0
[nodemon] app crashed - waiting for file changes before starting...

2023-09-18 18:54 UTC, NataliaHal commented
[nodemon] restarting due to changes...
[nodemon] starting `node ./server.js`
C:\node.js.home-work\nodejs-homework-rest-api\routes\api\users.js:22
router.post("/register", validateBody(registerSchema), registerController);
                         ^

TypeError: validateBody is not a function
    at Object.<anonymous> (C:\node.js.home-work\nodejs-homework-rest-api\routes\api\users.js:22:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\node.js.home-work\nodejs-homework-rest-api\app.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0
[nodemon] app crashed - waiting for file changes before starting...

2023-09-18 18:55 UTC, NataliaHal commented
не запускається сервер, допоможіть будь ласка, бо не можу далі виконати завдання

2023-09-18 20:57 UTC, NataliaHal commented
запустився сервер

2023-09-21 22:02 UTC, NataliaHal commented
Перевірте будь ласка роботу, в мене написаний весь код, але аватар не завантажується.

2023-09-22 06:23 UTC, KhYulian commented on controllers/authController.js
> +      console.log("Email");
```suggestion
```

2023-09-22 06:23 UTC, KhYulian commented on controllers/authController.js
> +    if (user === null) {
```suggestion
    if (!user) {
```

2023-09-22 06:24 UTC, KhYulian commented on controllers/authController.js
> +    if (user === null) {
виправте усюди

2023-09-22 06:24 UTC, KhYulian commented on controllers/authController.js
> +      console.log("Password");
логи видаліть

2023-09-22 06:24 UTC, KhYulian commented on middlewares/authenticate.js
> +    next(new Error("Unauthorized"));
якщо у вас є httpError чому не використовуєте?

2023-09-22 06:24 UTC, KhYulian commented on middlewares/validateBody.js
> +  return func;
```suggestion
  return (req, res, next) => {
    const { error } = schema.validate(req.body);
    if (error) {
      return next(new HttpError(400, error.message));
    }
    next();
  };
```

2023-09-22 08:54 UTC, NataliaHal commented
Правки внесла, але тепер роути взагалі не працюють. Це помилка в Postmsn {
    "message": "Cannot read properties of undefined (reading 'findOne')"
}  це помилка в терміналі POST /api/users/register 500 46.972 ms - 69     на 69 строці module.exports = router;

2023-09-22 10:02 UTC, KhYulian commented
Перевірте як ви імпортуєте \ експортуєте моделі усюди де вони використовуються

2023-09-22 15:10 UTC, KhYulian commented on routes/api/users.js
> -  ],
для валідації використовуйте виключно joi

2023-09-22 15:10 UTC, KhYulian commented on routes/api/users.js
> -);
контролери мають бути в окрему файлі

2023-09-22 15:10 UTC, KhYulian requested changes
Ви закоментували \ видалили функціонал, пов'язаний із юзером це не фікс

2023-09-22 16:49 UTC, KhYulian commented on routes/api/users.js
> +  }
чому ця частина коду не в контроллері?

2023-09-22 16:49 UTC, KhYulian commented on routes/api/users.js
> +  ctrl.register(req, res);
так не робіть. викликати контролер таким чином погана практика

2023-09-22 16:50 UTC, KhYulian commented on routes/api/users.js
> +router.post("/register", jsonParser, (req, res) => {
router.post("/register", jsonParser,  ctrl.register)

2023-09-23 05:35 UTC, KhYulian commented on controllers/authController.js
> +
а схеми ви для чого сюди винесли? Схеми joi окремо

2023-09-23 05:44 UTC, merged